- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-isort
  rev: master
  hooks:
  - id: isort
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    language_version: python3.6
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: flake8
    additional_dependencies: ["flake8-blind-except", "flake8-bugbear", "flake8-builtins",
                              "flake8-comprehensions", "flake8-debugger", "flake8-isort",
                              "flake8-quotes", "flake8-string-format"]
